#pragma once

#define FG_BLACK "0;30;"
#define FG_DARKGRAY "1;30;"
#define FG_DARKRED "0;31;"
#define FG_LIGHTRED "1;31;"
#define FG_DARKGREEN "0;32;"
#define FG_LIGHTGREEN "1;32;"
#define FG_DARKYELLOW "0;33;"
#define FG_LIGHTYELLOW "1;33;"
#define FG_DARKBLUE "0;34;"
#define FG_LIGHTBLUE "1;34;"
#define FG_DARKPINK "0;35;"
#define FG_LIGHTPINK "1;35;"
#define FG_DARKCYAN "0;36;"
#define FG_LIGHTCYAN "1;36;"
#define FG_LIGHTGRAY "0;37;"
#define FG_WHITE "1;37;"

#define BG_BLACK "40"
#define BG_DARKGRAY "100"
#define BG_DARKRED "41"
#define BG_LIGHTRED "101"
#define BG_DARKGREEN "42"
#define BG_LIGHTGREEN "102"
#define BG_DARKYELLOW "43"
#define BG_LIGHTYELLOW "103"
#define BG_DARKBLUE "44"
#define BG_LIGHTBLUE "104"
#define BG_DARKPINK "45"
#define BG_LIGHTPINK "105"
#define BG_DARKCYAN "46"
#define BG_LIGHTCYAN "106"
#define BG_LIGHTGRAY "47"
#define BG_WHITE "107"

#define DC_NONE ";01"
#define DC_UNDERLINE ";04"
#define DC_INVERT ";07"